# Generated by Django 2.1.7 on 2019-03-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='desc_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfr_desc', models.TextField()),
                ('hw_desc', models.TextField()),
                ('sw_desc', models.TextField()),
                ('serial_num', models.TextField()),
                ('dp_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='flow_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('table_id', models.TextField()),
                ('duration_sec', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('idle_timeout', models.IntegerField()),
                ('hard_timeout', models.IntegerField()),
                ('packet_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='port_stats',
            fields=[
                ('device_id', models.TextField()),
                ('port_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rx_packets', models.IntegerField()),
                ('tx_packets', models.IntegerField()),
                ('rx_dropped', models.IntegerField()),
                ('tx_dropped', models.IntegerField()),
                ('rx_errors', models.IntegerField()),
                ('tx_errors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='queue_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_no', models.IntegerField()),
                ('queue_id', models.IntegerField()),
                ('tx_bytes', models.IntegerField()),
                ('tx_packets', models.IntegerField()),
                ('tx_errors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='table_stats',
            fields=[
                ('table_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('wildcards', models.IntegerField()),
                ('max_entries', models.IntegerField()),
                ('active_count', models.IntegerField()),
                ('lookup_count', models.IntegerField()),
                ('matched_count', models.IntegerField()),
            ],
        ),
    ]
