# Generated by Django 2.1.7 on 2019-04-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appmonitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow_stats',
            name='length',
        ),
    ]
