# Generated by Django 2.1.7 on 2019-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmonitor', '0002_remove_flow_stats_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port_stats',
            name='port_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
