# Generated by Django 2.0.13 on 2019-03-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(blank=True, null=True)),
                ('syslog', models.TextField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='total_traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rx_bytes', models.IntegerField(default=0)),
                ('total_tx_bytes', models.IntegerField(default=0)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
