# Generated by Django 2.1.7 on 2019-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDNMonitorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='links_table',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('status', models.BooleanField()),
                ('source_id', models.TextField()),
                ('target_id', models.TextField()),
                ('status_changed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='nodes_table',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('label', models.TextField()),
            ],
        ),
    ]
