# Generated by Django 2.1.7 on 2019-03-31 16:01

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SDNMonitorApp', '0003_remove_links_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='links_table',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='up', max_length=100, no_check_for_status=True),
        ),
    ]
