# Generated by Django 2.1.7 on 2019-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDNMonitorApp', '0004_links_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='links_table',
            name='source_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='links_table',
            name='target_port',
            field=models.IntegerField(default=0),
        ),
    ]
